services:
  # payload:
  #   image: node:20-alpine
  #   container_name: node-app
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - /home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "npm install && npm run dev"
  #   depends_on:
  #     - postgres #dont start the app unless the postgres enabled
  #   env_file:
  #     - .env

  # Postgres
  postgres:
    image: postgres:15-alpine
    container_name: quiz-postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quiz_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
